export const megaMenuStyles = {
  wrapper: "static",
  trigger: "inline-flex items-center gap-1 rounded-[var(--fm-radius-md)] px-3.5 py-2 font-sans text-[15px] font-medium text-[var(--fm-text-secondary)] transition-[background-color,color] duration-[var(--fm-motion-micro)] ease-[var(--fm-motion-ease)] hover:bg-[var(--fm-lime-soft)] hover:text-[var(--fm-text-primary)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--fm-lime)]/40",
  panel: "fixed left-[90vw] z-[120] w-[min(1180px,calc(100vw-32px))] -translate-x-1/2 -origin-top rounded-[var(--fm-radius-feature)] border border-[var(--fm-border)] bg-[var(--fm-surface)] shadow-[var(--fm-shadow-elevated)] backdrop-blur-xl",
  panelOpen: "mega-menu-panel--open",
  panelClosed: "mega-menu-panel--closed",
  header: "flex items-end justify-between gap-fm-6 border-b border-[var(--fm-border-soft)] px-fm-6 py-fm-5",
  headerEyebrow: "font-mono text-fm-label font-bold uppercase tracking-fm-label text-[var(--fm-lime)]",
  headerTitle: "mt-1 font-sans text-xl font-bold tracking-[-0.035em] text-[var(--fm-text-primary)]",
  headerDescription: "max-w-xl text-sm leading-relaxed text-[var(--fm-text-secondary)]",
  content: "grid grid-cols-1 gap-0 p-fm-3 sm:grid-cols-2 lg:grid-cols-4",
  country: "min-w-0 px-fm-3 py-fm-3 lg:border-r lg:border-[var(--fm-border-soft)] lg:last:border-r-0",
  countryTitle: "mb-fm-4 flex items-center gap-2.5 rounded-[var(--fm-radius-md)] border border-[var(--fm-border-soft)] bg-[var(--fm-surface-raised)] px-fm-3 py-fm-2.5 font-sans text-base font-bold tracking-[-0.015em] text-[var(--fm-text-primary)] shadow-[var(--fm-shadow-subtle)]",
  countryMarker: "h-2 w-2 flex-shrink-0 rounded-full bg-[var(--fm-lime)] shadow-[0_0_0_3px_var(--fm-lime-soft)]",
  serviceList: "space-y-fm-1",
  service: "min-w-0",
  serviceParent: "flex w-full items-center gap-2 rounded-[var(--fm-radius-sm)] px-fm-2 py-[7px] text-left font-sans text-[13px] font-semibold leading-snug text-[var(--fm-text-primary)] transition-[background-color,color] duration-[var(--fm-motion-micro)] ease-[var(--fm-motion-ease)] hover:bg-[var(--fm-lime-soft)] hover:text-[var(--fm-text-primary)] focus-visible:bg-[var(--fm-lime-soft)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--fm-lime)]/40",
  serviceParentIcon: "mt-0.5 grid h-6 w-6 flex-shrink-0 place-items-center rounded-[var(--fm-radius-sm)] bg-[var(--fm-graphite-deep)] text-[var(--fm-lime)]",
  nestedBox: "ml-fm-2 rounded-r-[var(--fm-radius-md)] border-l-2 border-[var(--fm-border-accent)] bg-[var(--fm-surface-raised)] px-fm-2 py-fm-2 shadow-[var(--fm-shadow-subtle)]",
  item: "group flex min-w-0 items-start gap-2 rounded-[var(--fm-radius-sm)] px-fm-2 py-[7px] transition-[background-color,color] duration-[var(--fm-motion-micro)] ease-[var(--fm-motion-ease)] hover:bg-[var(--fm-lime-soft)] focus-visible:bg-[var(--fm-lime-soft)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--fm-lime)]/40",
  itemIcon: "mt-0.5 grid h-6 w-6 flex-shrink-0 place-items-center rounded-[var(--fm-radius-sm)] bg-[var(--fm-graphite-deep)] text-[var(--fm-lime)]",
  itemTitle: "block font-sans text-[13px] font-semibold leading-snug text-[var(--fm-text-primary)] transition-[color] duration-[var(--fm-motion-micro)] ease-[var(--fm-motion-ease)] group-hover:text-[var(--fm-lime-bright)]",
  itemDescription: "mt-0.5 block text-xs leading-relaxed text-[var(--fm-text-secondary)]",
  mobileItem: "flex items-start gap-3 border-t border-[var(--fm-border)] py-3 pl-3 text-left transition-[background-color,color] duration-[var(--fm-motion-micro)] ease-[var(--fm-motion-ease)] hover:bg-[var(--fm-lime-soft)] focus-visible:bg-[var(--fm-lime-soft)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--fm-lime)]/40",
  mobileCountry: "border-t border-[var(--fm-border)] px-1 py-4",
  mobileCountryTitle: "mb-2 px-1 font-mono text-fm-label font-bold uppercase tracking-fm-label text-[var(--fm-text-tertiary)]",
  mobileService: "px-1",
  mobileServiceParent: "py-2 font-sans text-sm font-semibold text-[var(--fm-text-primary)]",
  mobileNestedBox: "ml-2 border-l-2 border-[var(--fm-border-accent)] pl-2",
};
