import Link from "next/link";
import { ArrowRight, Check, FileText, Globe, Buildings, ShieldCheck } from "@phosphor-icons/react/dist/ssr";
import { Card, SectionLabel } from "@/components/ui/design-system";
import { Button } from "@/components/ui/button";

const steps = [
  { number: "01", title: "Choose your service", description: "Tell us what you want to build. Start with a USA LLC, UK LTD, or another business service and select the option that fits your goals.", icon: Globe, label: "Choose" },
  { number: "02", title: "Complete your application", description: "Work through a guided application and provide the founder, company, and identity information required for your service.", icon: FileText, label: "Apply" },
  { number: "03", title: "We handle the process", description: "Our team reviews your information and coordinates the relevant formation, filing, and supporting service steps.", icon: ShieldCheck, label: "Process" },
  { number: "04", title: "Receive your documents", description: "Track your progress, receive your formation documents, and move on to the next stage of operating your business.", icon: Buildings, label: "Operate" },
];

const expectations = [
  "A guided application instead of a confusing filing process",
  "Clear progress through each stage of your service",
  "One place for your documents and application information",
  "A path from formation into banking, payments, and compliance",
];

export default function Page() {
  return ( 
    <main className="fm-page overflow-hidden">
      <section className="relative isolate border-b border-[var(--fm-border)] bg-[radial-gradient(circle_at_78%_18%,var(--fm-hero-glow),transparent_28%),linear-gradient(135deg,var(--fm-graphite-deep)_0%,var(--fm-surface)_100%)] px-5 pb-20 pt-24 sm:px-8 sm:pb-24 sm:pt-28 lg:pb-28 lg:pt-32">
        <div className="pointer-events-none absolute inset-0 opacity-40 [background-image:linear-gradient(var(--fm-hero-grid-line)_1px,transparent_1px),linear-gradient(90deg,var(--fm-hero-grid-line)_1px,transparent_1px)] [background-size:var(--fm-hero-grid-size)_var(--fm-hero-grid-size)] [mask-image:var(--fm-hero-grid-mask)]" />
        <div className="relative mx-auto grid max-w-[1400px] items-center gap-12 lg:grid-cols-[1.15fr_.85fr] lg:gap-20">
          <div className="max-w-[850px]"><SectionLabel>How it works</SectionLabel><h1 className="mt-5 font-display text-[clamp(3rem,6vw,5.9rem)] font-extrabold leading-[.94] tracking-[-.065em] text-[var(--fm-text-primary)]">From idea to operating business, without the guesswork.</h1><p className="mt-7 max-w-[650px] text-[17px] leading-8 text-[var(--fm-text-secondary)] sm:text-[19px]">Audvertax turns company formation into a clear, staged process. Choose a service, complete your application, let us handle the work, and keep moving.</p><div className="mt-9 flex flex-wrap gap-3"><Button render={<Link href="/services" />}>Explore services <ArrowRight weight="bold" className="h-4 w-4" /></Button><Button render={<Link href="/pricing" />} variant="outline">View pricing</Button></div></div>
          <div className="relative hidden min-h-[330px] lg:block"><div className="absolute inset-8 rounded-[var(--fm-radius-feature)] border border-[var(--fm-border)] bg-[var(--fm-surface)]/80 shadow-[var(--fm-shadow-elevated)] backdrop-blur-xl" /><div className="absolute left-1/2 top-1/2 grid h-32 w-32 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full border border-[var(--fm-lime)]/45 bg-[var(--fm-graphite-deep)] shadow-[0_0_0_18px_var(--fm-hero-glow-soft)]"><div className="text-center"><div className="font-mono text-[9px] uppercase tracking-[.18em] text-[var(--fm-text-tertiary)]">Workflow</div><div className="mt-2 text-xl font-bold text-[var(--fm-lime-bright)]">LIVE</div><div className="mx-auto mt-2 h-1.5 w-1.5 rounded-full bg-[var(--fm-lime)]" /></div></div>{["01 Choose","02 Apply","03 Process","04 Operate"].map((item,index)=><div key={item} className={`absolute ${["left-4 top-10","right-0 top-20","right-4 bottom-12","left-0 bottom-6"][index]} rounded-full border border-[var(--fm-border)] bg-[var(--fm-surface-raised)] px-4 py-2 font-mono text-[10px] font-bold uppercase tracking-[.12em] text-[var(--fm-text-secondary)] shadow-[var(--fm-shadow-subtle)]`}>{item}</div>)}</div>
        </div>
      </section>

      <section className="px-5 py-20 sm:px-8 sm:py-24 lg:py-28"><div className="mx-auto max-w-[1400px]"><div className="mb-12 max-w-[650px]"><SectionLabel>The process</SectionLabel><h2 className="mt-3 font-display text-4xl font-extrabold tracking-[-.055em] text-[var(--fm-text-primary)] sm:text-5xl">Four stages. One clear path.</h2><p className="mt-4 text-fm-body text-[var(--fm-text-secondary)]">Every stage has a clear purpose, so you always know what happens next.</p></div><div className="relative grid gap-4 md:grid-cols-2 lg:grid-cols-4 lg:gap-fm-5"><div className="pointer-events-none absolute left-[12%] right-[12%] top-[76px] hidden h-px bg-gradient-to-r from-transparent via-[var(--fm-lime)]/35 to-transparent lg:block" />{steps.map(({number,title,description,icon:Icon,label})=><Card key={number} variant="interactive" tone="default" className="group relative border-t-0 p-6 sm:p-7"><div className="relative flex items-center justify-between"><div className="grid h-12 w-12 place-items-center rounded-[var(--fm-radius-md)] border border-[var(--fm-lime)]/25 bg-[var(--fm-lime)]/10 text-[var(--fm-lime)]"><Icon className="h-5 w-5" /></div><span className="font-mono text-[11px] font-bold tracking-[.12em] text-[var(--fm-card-muted)]">{number}</span></div><div className="mt-7 fm-label text-[10px]">{label}</div><h3 className="mt-2 font-display text-xl font-extrabold tracking-[-.03em] text-[var(--fm-card-text)]">{title}</h3><p className="mt-3 text-sm leading-6 text-[var(--fm-card-muted)]">{description}</p></Card>)}</div></div></section>

      <section className="px-5 pb-20 sm:px-8 sm:pb-24 lg:pb-28"><Card variant="elevated" tone="default" className="mx-auto grid max-w-[1400px] overflow-hidden p-0 lg:grid-cols-[1fr_.9fr]"><div className="p-8 sm:p-10 lg:p-14"><SectionLabel>What you can expect</SectionLabel><h2 className="mt-4 max-w-[600px] font-display text-3xl font-extrabold tracking-[-.045em] text-[var(--fm-card-text)] sm:text-4xl">A guided experience built around the work you actually need to get done.</h2><div className="mt-8 grid gap-4">{expectations.map(item=><div key={item} className="flex items-start gap-3 text-sm leading-6 text-[var(--fm-card-muted)]"><span className="mt-0.5 grid h-5 w-5 flex-shrink-0 place-items-center rounded-full bg-[var(--fm-lime)]/12 text-[var(--fm-lime)]"><Check className="h-3 w-3" /></span>{item}</div>)}</div></div><div className="relative flex min-h-[330px] items-end overflow-hidden bg-[var(--fm-lime)] p-8 text-[var(--fm-graphite-deep)] sm:p-10 lg:p-14"><div className="absolute -right-24 -top-24 h-72 w-72 rounded-full border border-[var(--fm-graphite-deep)]/15 shadow-[0_0_0_28px_rgba(16,19,16,.04),0_0_0_56px_rgba(16,19,16,.025)]" /><div className="relative"><div className="font-mono text-[10px] font-bold uppercase tracking-[.16em] text-[var(--fm-graphite-deep)]/60">Your next move</div><div className="mt-3 font-display text-3xl font-extrabold tracking-[-.045em]">Start with the service that matches your goal.</div><Button render={<Link href="/services" />} variant="card" className="mt-7">Browse services <ArrowRight weight="bold" className="h-4 w-4" /></Button></div></div></Card></section>
    </main>
  );
}
