"use client";

import Link from "next/link";
import { ArrowRight, ArrowUpRight, Building2, CheckCircle2, CreditCard, FileText, Landmark } from "lucide-react";
import { serviceCatalog } from "@/lib/services/commercial-catalog";
import { Card } from "@/components/ui/design-system";

const icons = [Building2, FileText, Landmark, CreditCard];
const rails = ["FORMATION", "TAX", "BANKING", "PAYMENTS", "COMPLIANCE", "GLOBAL RAILS"];

export default function Services() {
  return (
    <main className="fm-page overflow-hidden bg-[var(--fm-graphite-deep)] text-[var(--fm-text-primary)]">
      <section className="relative isolate min-h-[82dvh] overflow-hidden bg-[var(--fm-graphite-deep)] px-fm-6 pb-fm-20 pt-28 sm:px-fm-10 lg:px-fm-14 lg:pt-32">
        <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_76%_42%,var(--fm-hero-glow),transparent_31%),linear-gradient(110deg,var(--fm-graphite-deep)_0%,var(--fm-graphite)_55%,var(--fm-graphite-deep)_100%)]" />
        <div className="pointer-events-none absolute inset-0 opacity-20 [background-image:linear-gradient(color-mix(in_srgb,var(--fm-lime)_8%,transparent)_1px,transparent_1px),linear-gradient(90deg,color-mix(in_srgb,var(--fm-lime)_8%,transparent)_1px,transparent_1px)] [background-size:64px_64px]" />
        <div className="relative z-[2] mx-auto grid min-h-[62dvh] w-full max-w-[1400px] items-center gap-fm-12 lg:grid-cols-[1fr_.85fr]">
          <div className="max-w-[800px]">
            <div className="mb-7 inline-flex items-center gap-3 rounded-[var(--fm-radius-pill)] border border-[var(--fm-lime)]/25 bg-[var(--fm-lime)]/[.07] px-4 py-2.5 font-mono text-[10px] font-bold uppercase tracking-[.16em] text-[var(--fm-lime-bright)]"><span className="h-2 w-2 rounded-full bg-[var(--fm-lime)]" />Business infrastructure / services</div>
            <h1 className="max-w-[10ch] font-display font-bold tracking-[-.065em]" style={{ fontSize: "clamp(52px,7vw,94px)", lineHeight: .94 }}>Build the <span className="text-[var(--fm-lime)]">infrastructure</span> behind your business.</h1>
            <p className="mt-7 max-w-[650px] text-[16px] leading-[1.75] text-[var(--fm-text-secondary)] sm:text-[18px]">Formation, tax, banking and payment infrastructure—connected into one guided path for founders building across borders.</p>
            <div className="mt-9 flex flex-wrap gap-fm-3"><a href="#services" className="group inline-flex items-center gap-3 rounded-[var(--fm-radius-pill)] bg-[var(--fm-lime)] px-6 py-4 text-[15px] font-bold text-[var(--fm-graphite-deep)] transition-transform duration-[var(--fm-motion-component)] ease-[var(--fm-motion-ease)] hover:-translate-y-1 hover:bg-[var(--fm-lime-bright)]">Explore services <ArrowUpRight className="h-5 w-5 transition-transform duration-[var(--fm-motion-micro)] ease-[var(--fm-motion-ease)] group-hover:translate-x-1 group-hover:-translate-y-1" /></a><Link href="/how-it-works" className="inline-flex items-center gap-3 rounded-[var(--fm-radius-pill)] border border-[var(--fm-border)] bg-[var(--fm-surface)]/60 px-6 py-4 text-[15px] font-semibold text-[var(--fm-text-primary)] transition-[transform,border-color] duration-[var(--fm-motion-component)] ease-[var(--fm-motion-ease)] hover:-translate-y-1 hover:border-[var(--fm-border-accent)]">See the process <span className="font-mono text-[10px] text-[var(--fm-text-tertiary)]">01—05</span></Link></div>
          </div>
          <div className="relative hidden min-h-[480px] items-center justify-center lg:flex"><div className="absolute h-[420px] w-[420px] rounded-full bg-[var(--fm-hero-glow-soft)] blur-[var(--fm-hero-glow-blur)]" /><div className="relative h-[390px] w-[390px] rounded-full border border-[var(--fm-lime)]/15"><div className="absolute inset-[12%] rounded-full border border-dashed border-[var(--fm-lime)]/25" /><div className="absolute inset-[24%] rounded-full border border-[var(--fm-lime)]/20" /><div className="absolute left-1/2 top-[4%] h-[92%] w-px -translate-x-1/2 bg-[var(--fm-lime)]/10" /><div className="absolute left-[4%] top-1/2 h-px w-[92%] -translate-y-1/2 bg-[var(--fm-lime)]/10" />{[["50%","7%"],["84%","50%"],["50%","91%"],["16%","50%"]].map(([left, top], i) => <span key={i} className="absolute h-2.5 w-2.5 rounded-full bg-[var(--fm-lime)] shadow-[0_0_0_6px_color-mix(in_srgb,var(--fm-lime)_8%,transparent)]" style={{ left, top }} />)}<div className="absolute left-1/2 top-1/2 flex h-36 w-36 -translate-x-1/2 -translate-y-1/2 flex-col items-center justify-center rounded-full border border-[var(--fm-lime)]/30 bg-[var(--fm-graphite)]/90 text-center shadow-[var(--fm-shadow-elevated)] backdrop-blur-md"><span className="font-mono text-[9px] uppercase tracking-[.18em] text-[var(--fm-text-tertiary)]">Audvertax</span><strong className="mt-2 text-2xl font-bold text-[var(--fm-lime-bright)]">RAILS</strong><span className="mt-2 h-1.5 w-1.5 rounded-full bg-[var(--fm-lime)]" /></div></div><div className="absolute bottom-0 left-1/2 w-full -translate-x-1/2 overflow-hidden border-y border-[var(--fm-border)] py-3 font-mono text-[9px] uppercase tracking-[.14em] text-[var(--fm-text-tertiary)]"><div className="flex w-max gap-fm-12">{rails.concat(rails).map((item, i) => <span key={i}>{item}</span>)}</div></div></div>
        </div>
      </section>

      <section id="services" className="bg-[var(--fm-graphite-deep)] px-fm-6 py-fm-20 text-[var(--fm-text-primary)] sm:px-fm-10 sm:py-fm-24 lg:px-fm-14 lg:py-fm-28"><div className="mx-auto max-w-[1400px]"><div className="mb-12 flex flex-col justify-between gap-fm-5 lg:flex-row lg:items-end"><div><div className="font-mono text-[10px] font-bold uppercase tracking-[.17em] text-[var(--fm-lime)]">01 / Service stack</div><h2 className="mt-3 max-w-[760px] font-display text-4xl font-bold tracking-[-.055em] sm:text-5xl lg:text-6xl">Choose the rail your business needs next.</h2></div><p className="max-w-[360px] text-sm leading-6 text-[var(--fm-text-secondary)]">Each service is designed to connect with the next step, so your business infrastructure grows as one system.</p></div><div className="grid gap-fm-4 md:grid-cols-2">{serviceCatalog.map((service, i) => { const Icon = icons[i % icons.length]; return <Card key={service.slug} variant="interactive" tone="dark" className="group relative min-h-[330px] overflow-hidden p-7 sm:p-9"><Link href={`/services/${service.slug}`} className="absolute inset-0 z-[1]" aria-label={`Explore ${service.name}`} /><div className="absolute -right-20 -top-20 h-48 w-48 rounded-full border border-[var(--fm-lime)]/20 transition-transform duration-[var(--fm-motion-component)] ease-[var(--fm-motion-ease)] group-hover:scale-110" /><div className="relative z-[2] flex h-full flex-col justify-between pointer-events-none"><div><div className="flex items-center justify-between"><span className="grid h-12 w-12 place-items-center rounded-[var(--fm-radius-md)] border border-[var(--fm-lime)]/25 bg-[var(--fm-lime)]/10 text-[var(--fm-lime)]"><Icon className="h-5 w-5" /></span><span className="font-mono text-[10px] font-bold tracking-[.16em] text-[var(--fm-text-tertiary)]">{String(i + 1).padStart(2, "0")}</span></div><h3 className="mt-8 max-w-[520px] font-display text-3xl font-bold tracking-[-.045em] text-[var(--fm-card-text)] sm:text-4xl">{service.name}</h3><p className="mt-4 max-w-[520px] text-[15px] leading-7 text-[var(--fm-card-muted)]">{service.shortDescription}</p></div><span className="mt-9 inline-flex items-center gap-2 text-sm font-bold text-[var(--fm-lime-bright)]">Explore service <ArrowRight className="h-4 w-4 transition-transform duration-[var(--fm-motion-micro)] ease-[var(--fm-motion-ease)] group-hover:translate-x-1" /></span></div></Card> })}</div></div></section>

      <section className="bg-[var(--fm-graphite-deep)] px-fm-6 py-fm-20 text-[var(--fm-text-primary)] sm:px-fm-10 sm:py-fm-24 lg:px-fm-14 lg:py-fm-28"><div className="mx-auto max-w-[1400px]"><div className="grid gap-fm-12 lg:grid-cols-[.9fr_1.1fr] lg:gap-fm-24"><div><div className="font-mono text-[10px] font-bold uppercase tracking-[.17em] text-[var(--fm-lime)]">02 / Connected by design</div><h2 className="mt-4 max-w-[620px] font-display text-4xl font-bold tracking-[-.055em] sm:text-5xl">One business. Multiple rails. One guided experience.</h2></div><div className="grid gap-0 border-t border-[var(--fm-border)]">{["Guided applications", "Centralized documents", "Payment readiness", "Compliance visibility"].map((item, i) => <div key={item} className="flex items-center justify-between border-b border-[var(--fm-border)] py-6"><div className="flex items-center gap-5"><span className="font-mono text-[10px] text-[var(--fm-text-tertiary)]">0{i + 1}</span><strong className="text-base sm:text-lg">{item}</strong></div><CheckCircle2 className="h-5 w-5 text-[var(--fm-lime)]" /></div>)}</div></div></div></section>
      <section className="bg-[var(--fm-lime-soft)] px-fm-6 py-fm-16 text-[var(--fm-graphite-deep)] sm:px-fm-10 lg:px-fm-14"><div className="mx-auto flex max-w-[1400px] flex-col justify-between gap-fm-8 lg:flex-row lg:items-end"><div><div className="font-mono text-[10px] font-bold uppercase tracking-[.17em] text-[var(--fm-graphite)]">03 / Next move</div><h2 className="mt-3 max-w-[720px] font-display text-4xl font-bold tracking-[-.055em] sm:text-5xl">Not sure which service comes first?</h2></div><Link href="/how-it-works" className="group inline-flex w-fit items-center gap-3 rounded-[var(--fm-radius-pill)] bg-[var(--fm-graphite-deep)] px-6 py-4 text-sm font-bold text-[var(--fm-text-primary)] transition-transform duration-[var(--fm-motion-component)] ease-[var(--fm-motion-ease)] hover:-translate-y-1 hover:bg-[var(--fm-graphite)]">See how it works <ArrowUpRight className="h-5 w-5 transition-transform duration-[var(--fm-motion-micro)] ease-[var(--fm-motion-ease)] group-hover:translate-x-1 group-hover:-translate-y-1" /></Link></div></section>
    </main>
  );
}
